# Generated by Django 3.2.7 on 2021-12-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_rename_name_image_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
    ]
