# Generated by Django 3.2.7 on 2021-12-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_rename_image_name_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='caption',
        ),
    ]
