# Generated by Django 3.2.7 on 2021-12-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_rename_description_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
