# Generated by Django 3.2.7 on 2021-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20211205_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted_on',
            field=models.DateTimeField(default=''),
        ),
    ]
