# Generated by Django 3.2.8 on 2021-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_auto_20211207_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
